### ISSUE TITLE
Fallout 4 importing error

### ISSUE THREAD

**Issue by InboundCrib3** [niftools/blender_niftools_addon#638]
Anytime I try importing a model from Fallout 4 into blender I get this error:

Python: Traceback (most recent call last):
  File "C:\Users\Inbound\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_scene_niftools\nif_import.py", line 102, in execute
    nifgen.spells.nif.fix.SpellMergeSkeletonRoots(data=NifData.data).recurse()
  File "C:\Users\Inbound\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_scene_niftools\dependencies\pyffi\spells\__init__.py", line 285, in recurse
    if self.dataentry():
       ^^^^^^^^^^^^^^^^
  File "C:\Users\Inbound\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_scene_niftools\dependencies\nifgen\spells\nif\fix.py", line 433, in dataentry
    for branch in self.data.get_global_iterator():
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NifFile' object has no attribute 'get_global_iterator'

**Comment by InboundCrib3** [comment]
Nvm i didnt seee that it only works in 3.6 and not 4.0
